// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvpQ_rjjqoUZuuRRWQOD-vcBLdhhWYJ4I',
    appId: '1:202463921073:web:b3c2823c48f328443cf390',
    messagingSenderId: '202463921073',
    projectId: 'brew-crew-e0fb8',
    authDomain: 'brew-crew-e0fb8.firebaseapp.com',
    storageBucket: 'brew-crew-e0fb8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCEisRXIIY_TsHBxYn8tFwOWRle6Lk8P8',
    appId: '1:202463921073:android:de30efe74d7b59a73cf390',
    messagingSenderId: '202463921073',
    projectId: 'brew-crew-e0fb8',
    storageBucket: 'brew-crew-e0fb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr5LekvrPrdzMXZMUch2SRROkR3iXxJQI',
    appId: '1:202463921073:ios:f7104b6d264a1deb3cf390',
    messagingSenderId: '202463921073',
    projectId: 'brew-crew-e0fb8',
    storageBucket: 'brew-crew-e0fb8.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
